[package]
name = "Tradgance-API"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.44.2", features = ["full"] }
axum = "0.8.3"
dotenv = "0.15.0"
serde = { version = "1.0.219", features = ["derive"] }